<a href="https://colab.research.google.com/github/irafilina1990-sudo/Tarefa_Database/blob/main/13_de_outubro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
students_info = {
    'name': 'Alice',
    'age': 22,
    'cource': 'DA'
}
print('исходный словарь: \n', students_info)

исходный словарь:
 {'name': 'Alice', 'age': 22, 'cource': 'DA'}

In [5]:
"""
форматированная строка позволяет подставлять значения переменной в фигурных скобках
- {переменная},
при этом не делаем разрыв строки
чтобы строка стала форматированной, нужно поставить фраг f
"""

#comment

print(f'исходный словарь: \n {students_info}')

исходный словарь:
 {'name': 'Alice', 'age': 22, 'cource': 'DA'}

In [4]:
students_info

{'name': 'Alice', 'age': 22, 'cource': 'DA'}

In [6]:
students_info['major'] = 'Computer Science'
print(f'Словарь после добавления key-value: \n {students_info}')

Словарь после добавления key-value:
 {'name': 'Alice', 'age': 22, 'cource': 'DA', 'major': 'Computer Science'}

In [7]:
students_data = {
    'name': ['Alice', 'Bob', 'Charle'],
    'age': [22, 30, 40],
    'cource': ['DA', 'Computer Sience', 'Physics']
}
print(f"исходный словарь: \n {students_data}" )

исходный словарь:
 {'name': ['Alice', 'Bob', 'Charle'], 'age': [22, 30, 40], 'cource': ['DA', 'Computer Sience', 'Physics']}

In [8]:
students_df = pd.DataFrame(students_data)

In [9]:
print(f'ДатаФрейм из словаря: \n {students_df}')

ДатаФрейм из словаря:
      name  age           cource
0   Alice   22               DA
1     Bob   30  Computer Sience
2  Charle   40          Physics

In [11]:
# .ipymp позволяет в отличие от "классического" python (.py) позволяет делать вывод значения, не прописывая функцию print()
students_df

     name  age           cource
0   Alice   22               DA
1     Bob   30  Computer Sience
2  Charle   40          Physics

In [12]:
students_df['cource']

0                 DA
1    Computer Sience
2            Physics
Name: cource, dtype: object

In [13]:
students_df['Grade'] = ['A', 'B', 'C']

In [14]:
students_df

     name  age           cource Grade
0   Alice   22               DA     A
1     Bob   30  Computer Sience     B
2  Charle   40          Physics     C

In [15]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   cource  3 non-null      object
 3   Grade   3 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes

In [16]:
students_df.shape

(3, 4)

In [17]:
students_df

     name  age           cource Grade
0   Alice   22               DA     A
1     Bob   30  Computer Sience     B
2  Charle   40          Physics     C

In [18]:
students_df.dtypes

name      object
age        int64
cource    object
Grade     object
dtype: object

In [22]:
from numpy import e
#запись в Exel и чтение из Exel

excel_path = 'students1.xlsx'
try:
  students_df.to_excel(excel_path, index=False, sheet_name='students')
  print(f"файл Excel успешно записан: {excel_path}")
except Exception as e:
  print(f'\n [WAENING] Не удалось записать файл Excel')
  print("Исключение :\n", repr(e))

файл Excel успешно записан: students1.xlsx

In [25]:
df_from_excel = pd.read_excel(excel_path, sheet_name='students')
df_from_excel

     name  age           cource Grade
0   Alice   22               DA     A
1     Bob   30  Computer Sience     B
2  Charle   40          Physics     C