<a href="https://colab.research.google.com/github/irafilina1990-sudo/Tarefa_Database/blob/main/SQzL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
users = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6],
    "name": ["Ivan", "Gleb", "Sergey", "Andrew", "Bob", "Tom"],
    "email": [
        "ivan@example.com",
        "gleb@example.com",
        "sergey@example.com",
        "andrew@example.com",
        "bob@example.com",
        "tom@example.com"
    ],
    "age": [25, 26, 28, 24, 25, 29],
    "country": ["RUS", "RUS", "RUS", "RUS", "USA", "USA"],
    "balance": [100000.00, 90000.00, 90000.00, 95000.00, 100000.00, 110000.00]
})

users

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

In [3]:
print("Размер таблицы users:", users.shape)
print("Количество строк:", users.shape[0])
print("Количество столбцов:", users.shape[1])
print("Названия столбцов:", list(users.columns))

Размер таблицы users: (6, 6)
Количество строк: 6
Количество столбцов: 6
Названия столбцов: ['id', 'name', 'email', 'age', 'country', 'balance']

In [4]:
users.dtypes

id           int64
name        object
email       object
age          int64
country     object
balance    float64
dtype: object

In [5]:
names = users["name"]

print(names)
print("\nТип объекта:", type(names))
print("Тип данных внутри Series:", names.dtype)

0      Ivan
1      Gleb
2    Sergey
3    Andrew
4       Bob
5       Tom
Name: name, dtype: object

Тип объекта: <class 'pandas.core.series.Series'>
Тип данных внутри Series: object

In [6]:
users[["id", "name", "age"]]

   id    name  age
0   1    Ivan   25
1   2    Gleb   26
2   3  Sergey   28
3   4  Andrew   24
4   5     Bob   25
5   6     Tom   29

In [7]:
users[users["age"] > 26]

   id    name               email  age country   balance
2   3  Sergey  sergey@example.com   28     RUS   90000.0
5   6     Tom     tom@example.com   29     USA  110000.0

In [8]:
users["age"] > 26

0    False
1    False
2     True
3    False
4    False
5     True
Name: age, dtype: bool

In [9]:
users[(users["age"] > 26) & (users["country"] == "RUS")]

   id    name               email  age country  balance
2   3  Sergey  sergey@example.com   28     RUS  90000.0

In [10]:
users.sort_values("balance", ascending=False)

   id    name               email  age country   balance
5   6     Tom     tom@example.com   29     USA  110000.0
0   1    Ivan    ivan@example.com   25     RUS  100000.0
4   5     Bob     bob@example.com   25     USA  100000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0

In [11]:
users[users["balance"].between(95000, 110000)]

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

In [12]:
print("Количество пользователей:", len(users))
print("Средний баланс:", users["balance"].mean())
print("Сумма балансов:", users["balance"].sum())
print("Минимальный баланс:", users["balance"].min())
print("Максимальный баланс:", users["balance"].max())

Количество пользователей: 6
Средний баланс: 97500.0
Сумма балансов: 585000.0
Минимальный баланс: 90000.0
Максимальный баланс: 110000.0

In [13]:
users.groupby("country").agg(
    users_count=("id", "count"),
    avg_balance=("balance", "mean"),
    total_balance=("balance", "sum")
).reset_index()

  country  users_count  avg_balance  total_balance
0     RUS            4      93750.0       375000.0
1     USA            2     105000.0       210000.0

In [14]:
# Найдём пользователей, у которых email находится на домене example.com
users[users["email"].str.contains("example.com", regex=False)]

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

In [15]:
# Приведём имена к нижнему регистру
users["name_lower"] = users["name"].str.lower()

users[["name", "name_lower"]]

     name name_lower
0    Ivan       ivan
1    Gleb       gleb
2  Sergey     sergey
3  Andrew     andrew
4     Bob        bob
5     Tom        tom

In [16]:
users_for_types = users[["id", "name", "age", "balance"]].copy()

# Представим, что возраст случайно стал текстом
users_for_types["age_as_text"] = users_for_types["age"].astype(str)

users_for_types[["name", "age", "age_as_text"]]

     name  age age_as_text
0    Ivan   25          25
1    Gleb   26          26
2  Sergey   28          28
3  Andrew   24          24
4     Bob   25          25
5     Tom   29          29

In [17]:
print("Тип age:", users_for_types["age"].dtype)
print("Тип age_as_text:", users_for_types["age_as_text"].dtype)

Тип age: int64
Тип age_as_text: object

In [18]:
# Вернём возраст обратно в числовой тип
users_for_types["age_recovered"] = users_for_types["age_as_text"].astype(int)

users_for_types[["name", "age_as_text", "age_recovered"]]

     name age_as_text  age_recovered
0    Ivan          25             25
1    Gleb          26             26
2  Sergey          28             28
3  Andrew          24             24
4     Bob          25             25
5     Tom          29             29

In [19]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.5)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 1.5 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [24]:
from sqlalchemy import create_engine

In [25]:
engine = create_engine("mysql+pymysql://root:root@localhost:3306/my_database")

In [26]:
query = (
     "SELECT id, name, email, age, country, balance "
     "FROM users "
     "WHERE country = 'RUS' "
     "ORDER BY balance DESC;"
 )

In [29]:
users[["name", "country", "balance"]]

     name country   balance
0    Ivan     RUS  100000.0
1    Gleb     RUS   90000.0
2  Sergey     RUS   90000.0
3  Andrew     RUS   95000.0
4     Bob     USA  100000.0
5     Tom     USA  110000.0

In [31]:
users[users["country"] == 'USA']

   id name            email  age country   balance name_lower
4   5  Bob  bob@example.com   25     USA  100000.0        bob
5   6  Tom  tom@example.com   29     USA  110000.0        tom

In [33]:
users[users["balance"] > 95000]

   id  name             email  age country   balance name_lower
0   1  Ivan  ivan@example.com   25     RUS  100000.0       ivan
4   5   Bob   bob@example.com   25     USA  100000.0        bob
5   6   Tom   tom@example.com   29     USA  110000.0        tom

In [34]:
users.sort_values("age", ascending=False)

   id    name               email  age country   balance name_lower
5   6     Tom     tom@example.com   29     USA  110000.0        tom
2   3  Sergey  sergey@example.com   28     RUS   90000.0     sergey
1   2    Gleb    gleb@example.com   26     RUS   90000.0       gleb
0   1    Ivan    ivan@example.com   25     RUS  100000.0       ivan
4   5     Bob     bob@example.com   25     USA  100000.0        bob
3   4  Andrew  andrew@example.com   24     RUS   95000.0     andrew

In [35]:
users.sort_values("age", ascending=True)

   id    name               email  age country   balance name_lower
3   4  Andrew  andrew@example.com   24     RUS   95000.0     andrew
0   1    Ivan    ivan@example.com   25     RUS  100000.0       ivan
4   5     Bob     bob@example.com   25     USA  100000.0        bob
1   2    Gleb    gleb@example.com   26     RUS   90000.0       gleb
2   3  Sergey  sergey@example.com   28     RUS   90000.0     sergey
5   6     Tom     tom@example.com   29     USA  110000.0        tom

In [38]:
users[users["country"] == "RUS"]["balance"].mean()

np.float64(93750.0)

In [39]:
users["balance_text"] = users["balance"].astype(str)
users[["name", "balance", "balance_text"]]

     name   balance balance_text
0    Ivan  100000.0     100000.0
1    Gleb   90000.0      90000.0
2  Sergey   90000.0      90000.0
3  Andrew   95000.0      95000.0
4     Bob  100000.0     100000.0
5     Tom  110000.0     110000.0

In [40]:
users["email_domain"] = users["email"].str.split("@").str[1]
users[["name", "email", "email_domain"]]

     name               email email_domain
0    Ivan    ivan@example.com  example.com
1    Gleb    gleb@example.com  example.com
2  Sergey  sergey@example.com  example.com
3  Andrew  andrew@example.com  example.com
4     Bob     bob@example.com  example.com
5     Tom     tom@example.com  example.com