<a href="https://colab.research.google.com/github/irafilina1990-sudo/Tarefa_Database/blob/main/%D0%9F%D0%971.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
# Бизнес-ситуации от директора (Extract)
business_problems = [
    "Клиенты уходят к конкурентам, хотя у нас цены ниже.",
    "Маркетинг потратил миллион на рекламу, а продаж в офлайне нет.",
    "На складах постоянно не хватает ходовых товаров, но лежат неликвиды.",
    "Сайт тормозит в пятницу вечером, мы теряем заказы.",
    "Мы совершенно не понимаем, кто наш идеальный покупатель."
]

# Создаем DataFrame
df = pd.DataFrame({
    'Бизнес-проблема': business_problems,
    'Тип аналитики': ['Продуктовая', 'Маркетинговая', 'Операционная', 'IT/Операционная', 'Продуктовая/Маркетинговая'],
    'Ключевая метрика (KPI)': ['...', '...', '...', '...', '...'],
    'Какие данные нужны (Источники)?': ['...', '...', '...', '...', '...']
})

# Задание: Замените '...' на свои значения, опираясь на лекционный материал.
# Пример: для первой проблемы метрика может быть 'Retention Rate' или 'NPS', а данные - 'CRM, история покупок'.

print("Итоговая таблица:")
display(df)

Итоговая таблица:

,Бизнес-проблема,Тип аналитики,Ключевая метрика (KPI),Какие данные нужны (Источники)?
0,"Клиенты уходят к конкурентам, хотя у нас цены ...",Продуктовая,...,...
1,"Маркетинг потратил миллион на рекламу, а прода...",Маркетинговая,...,...
2,На складах постоянно не хватает ходовых товаро...,Операционная,...,...
3,"Сайт тормозит в пятницу вечером, мы теряем зак...",IT/Операционная,...,...
4,"Мы совершенно не понимаем, кто наш идеальный п...",Продуктовая/Маркетинговая,...,...

In [4]:
import pandas as pd
# Бизнес-ситуации от директора (Extract)
business_problems = [
    "Клиенты уходят к конкурентам, хотя у нас цены ниже.",
    "Маркетинг потратил миллион на рекламу, а продаж в офлайне нет.",
    "На складах постоянно не хватает ходовых товаров, но лежат неликвиды.",
    "Сайт тормозит в пятницу вечером, мы теряем заказы.",
    "Мы совершенно не понимаем, кто наш идеальный покупатель."
]

# Создаем DataFrame
df = pd.DataFrame({
    'Бизнес-проблема': business_problems,
    'Тип аналитики': ['Продуктовая', 'Маркетинговая', 'Операционная', 'IT/Операционная', 'Продуктовая/Маркетинговая'],
    'Ключевая метрика (KPI)': ['Retention Rate', 'CTR, CPA', 'Out-of-Stock Rate, Obsolete/Slow-moving inventory ratio, Inventory Turnover', 'p95 Response Time, Conversion Rat, Bounce Rate, Estimated Lost Revenue', 'RFM-скор, LTV, CAC, Retention Rate'],
    'Какие данные нужны (Источники)?': ['CRM, история покупок', 'CRM, Яндекс Метрика', 'WMS (Warehouse Management System), ERP (например, 1С:УТ), исторические данные о продажах (POS/онлайн-заказы).', 'Яндекс.Метрика, Google Analytics, Web Vitals, APM-системы, логи Nginx', 'CRM, ERP/POS, система лояльности, веб-аналитика']
})

# Задание: Замените '...' на свои значения, опираясь на лекционный материал.
# Пример: для первой проблемы метрика может быть 'Retention Rate' или 'NPS', а данные - 'CRM, история покупок'.

print("Итоговая таблица:")
display(df)

Итоговая таблица:

,Бизнес-проблема,Тип аналитики,Ключевая метрика (KPI),Какие данные нужны (Источники)?
0,"Клиенты уходят к конкурентам, хотя у нас цены ...",Продуктовая,Retention Rate,"CRM, история покупок"
1,"Маркетинг потратил миллион на рекламу, а прода...",Маркетинговая,"CTR, CPA","CRM, Яндекс Метрика"
2,На складах постоянно не хватает ходовых товаро...,Операционная,"Out-of-Stock Rate, Obsolete/Slow-moving invent...","WMS (Warehouse Management System), ERP (наприм..."
3,"Сайт тормозит в пятницу вечером, мы теряем зак...",IT/Операционная,"p95 Response Time, Conversion Rat, Bounce Rate...","Яндекс.Метрика, Google Analytics, Web Vitals, ..."
4,"Мы совершенно не понимаем, кто наш идеальный п...",Продуктовая/Маркетинговая,"RFM-скор, LTV, CAC, Retention Rate","CRM, ERP/POS, система лояльности, веб-аналитика"